language: php
php:
  - 7.1

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build_production
  repo: LyseonTech/lyseontech.github.io
  target_branch: master
  keep-history: true
  email: travis-ci@lyseon.tech
  name: Travis-CI
  fqdn: lyseon.tech
  on:
    branch: master

before_deploy:
  - composer install
  - composer prod

script: /bin/true
